name: GFS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Adding pytest for more flexible testing in the future

    - name: Run unit tests
      run: |
        python test_gfs.py

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --max-line-length=100 --exclude=.git,__pycache__

  build:
    runs-on: ubuntu-latest
    needs: test  # Only run build if tests pass

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'


    - name: Build check
      run: |
        echo "Build step placeholder - all Python files are valid"
        python -c "import master, client, chunkserver, gfs"
